dist: xenial
language: python
python: 3.7

notifications:
  email: false

install:
  - pip install tox-travis
  - mkdir ~/.aws
  - printf "[default]\nregion = us-east-1\n[profile no-region]" > ~/.aws/config
  - printf "[default]\naws_access_key_id=${AWS_ACCESS_KEY_ID}\naws_secret_access_key=${AWS_SECRET_ACCESS_KEY}\n" > ~/.aws/credentials

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - tox

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
