service:
  name: yoki

plugins:
  - serverless-python-requirements

custom:
  instance_state_table: ${opt:stage, 'dev'}-${self:service}-ECSCtrInstanceState
  task_state_table: ${opt:stage, 'dev'}-${self:service}-ECSTaskState
  task_digest_table: ${opt:stage, 'dev'}-${self:service}-ECSTaskDigest
  pythonRequirements:
    dockerizePip: true


provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Batch*"
        - "dynamodb:GetItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
      Resource:
        - "arn:aws:dynamodb:*:*:table/${self:custom.instance_state_table}"
        - "arn:aws:dynamodb:*:*:table/${self:custom.task_state_table}"
        - "arn:aws:dynamodb:*:*:table/${self:custom.task_digest_table}"
    - Effect: "Allow"
      Action:
        - "ecr:DescribeRepositories"
        - "ecr:DescribeImages"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ecs:Describe*"
        - "ecs:List*"
        - "ecs:UpdateService"
        - "ecs:RegisterTaskDefinition"
        - "application-autoscaling:RegisterScalableTarget"
        - "iam:PassRole"
      Resource: "*"


functions:
  ecs-event-handler:
    name: ${self:service}-ecs-event-handler
    handler: lambdas.ecs_event.lambda_handler
    description: Store ECS events in dynamodb
    memorySize: 128
    timeout: 60
    reservedConcurrency: 1
    environment: ${file(.env.yml):lambda.environment}
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ecs"
            detail-type:
              - "ECS Task State Change"
              - "ECS Container Instance State Change"

resources:
  Resources:
    ECSCtrInstanceState:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.instance_state_table}
        AttributeDefinitions:
          - AttributeName: containerInstanceArn
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: containerInstanceArn
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: True

    ECSTaskState:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.task_state_table}
        AttributeDefinitions:
          - AttributeName: taskArn
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: taskArn
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: True

    ECSTaskDigest:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.task_digest_table}
        AttributeDefinitions:
          - AttributeName: deployment
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: deployment
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: True
